### PR TITLE
Exclude directories when filtered by extension

### PR DESCRIPTION
**Pull request by kodePhile**

### CODE REVIEW

**Comment by tcdng** [comment]
Your proposed changes filters out directories, right?

Like popular operating systems - Windows, Linux, etc - the `FileTransferServer` component considers directories (aka folders) as files too. A directory is considered a file albeit a pseudo one. This is why Java provides the `File.isFile()` and `File.isDirectory()` methods to check if a file object is an actual file or a directory. The `FileTransferServer.getLocalFileList()` method, and other similar methods defined in the component, sticks to this idea too.

If you look at the code, where the returned list is being populated, each new  `FileInfo` object is constructed with one of its arguments indicating whether the item is a true file.

```java
    @Override
    public List<FileInfo> getLocalFileList(FileTransferSetup fileTransferSetup) throws UnifyException {
        FileFilter fileFilter = new FileFilter(fileTransferSetup);
        File[] files = new File(fileTransferSetup.getLocalPath()).listFiles(fileFilter);
        if (files == null || files.length == 0) {
            return Collections.emptyList();
        }

        List<FileInfo> list = new ArrayList<FileInfo>();
        /* boolean filteredByExtension = !fileTransferSetup.getFileSuffixes().isEmpty(); */
        for (File file : files) {
            /* if (filteredByExtension && file.isDirectory()) {
                continue;
            } */
            list.add(new FileInfo(file.getName(), file.getAbsolutePath(), file.length(), file.lastModified(),
                    file.lastModified(), file.isFile(), file.isHidden()));
                                            ^^^^^^^^
        }

        return list;
    }
```
So suffixes returned by 'fileTransferSetup.getFileSuffixes()' can match directories. For instance, a suffix 'Logs' will match directories named 'PerfLogs' and 'AppLogs'.

If you look at the section of the `FileTransferSetup.Builder` class shown below, 'extension' is equivalent to 'suffix', which I suspect is the source of misinterpretation. 

```java
        public Builder filterByExtension(String extension) {
            if (fileSuffixes == null) {
                fileSuffixes = new HashSet<String>();
            }

            fileSuffixes.add(extension);
            return this;
        }

        public Builder filterByExtensions(Collection<String> extensions) {
            if (DataUtils.isNotBlank(extensions)) {
                if (fileSuffixes == null) {
                    fileSuffixes = new HashSet<String>();
                }

                fileSuffixes.addAll(extensions);
            }

            return this;
        }
```
It appears that the `filterByExtension()` and `filterByExtensions()` methods have to be deprecated for more explicit `filterBySuffix()` and `filterBySuffixes()` methods. Can you take on this?

**Comment by kodePhile** [comment]
<p>As you rightly mentioned, the naming was the cause of the misinterpretation.</p> <p>The first thing that came to mind when I saw the method was that it filters a directory by extension name until I tested it and saw it returned directories too. I will work on the proposed changes.</p> <p>I also noticed that filtering by these methods (I haven't tested for prefix yet) is case sensitive, is this intentional?</p>

**Comment by kodePhile** [comment]
Another thing I observe when I filter a directory by suffix is that it returns all the directories listed in this directory alongside the filtered files regardless of whether the directories match the suffix or not.
This is the code I tested with.
<pre>
    public static void main(String[] args) {
        try {
            FileTransferServer fileTransferServer = new FtpFileTransferServer();
            FileTransferSetup fileTransferSetup = FileTransferSetup.newBuilder().localPath("my root path/Desktop")
                    .filterByExtension("txt").build();
            List<FileInfo> fileInfoList = fileTransferServer.getLocalFileList(fileTransferSetup);
            for (FileInfo fileInfo : fileInfoList) {
                System.out.println(String.format("%s : %s", fileInfo.getFilename(), fileInfo.isFile()));
            }
        } catch (UnifyException e) {
            e.printStackTrace();
        }
    }
</pre>

And it returned:
<pre>
FormM mapping guide : false
MF20200025248.txt : true
MouseWithoutBorders : false
mysql8 manual installation guide.txt : true
</pre>

Note that 'FormM mapping guide' and 'MouseWithoutBorders' are directories and they do not match the 'txt' suffix criterion, however, they were still listed. I think this is what needs to be fixed, not excluding the whole directories like I was doing earlier.

**Comment by tcdng** [comment]
> As you rightly mentioned, the naming was the cause of the misinterpretation.
> 
> The first thing that came to mind when I saw the method was that it filters a directory by extension name until I tested it and saw it returned directories too. I will work on the proposed changes.
> 
> I also noticed that filtering by these methods (I haven't tested for prefix yet) is case sensitive, is this intentional?

File systems on Linux-like operating systems are case-sensitive; not so on Windows. If we use case-insensitive code in our implementation, we can not precisely filter out a specific file on Linux systems.

The question is, if we have two files on a Linux system - 'MouseTrap.txt' and 'MouSETrap.txt' - and we filter by prefix 'Mouse' , should both files be returned or just 'MouseTrap.txt'? This is not a problem on Windows.

On reflection, case sensitivity is bad for filtering on Windows, so you are right - the filtering mechanism should default to case-insensitive. We should have a flag in `FileTransferSetup` that defaults to false and can be set to true when constructing with `FileTransferSetup.Builder`. Then we update the `com.tcdng.unify.core.file.Filter` class and it's `accept()` method to accommodate this.

**Note:** Add your name (with optional email address) using the 'author' comment tag to the files you make changes to and to new files you create.

**Comment by tcdng** [comment]
> Another thing I observe when I filter a directory by suffix is that it returns all the directories listed in this directory alongside the filtered files regardless of whether the directories match the suffix or not.
> This is the code I tested with.
> 
>     public static void main(String[] args) {
>         try {
>             FileTransferServer fileTransferServer = new FtpFileTransferServer();
>             FileTransferSetup fileTransferSetup = FileTransferSetup.newBuilder().localPath("my root path/Desktop")
>                     .filterByExtension("txt").build();
>             List fileInfoList = fileTransferServer.getLocalFileList(fileTransferSetup);
>             for (FileInfo fileInfo : fileInfoList) {
>                 System.out.println(String.format("%s : %s", fileInfo.getFilename(), fileInfo.isFile()));
>             }
>         } catch (UnifyException e) {
>             e.printStackTrace();
>         }
>     }
> And it returned:
> 
> FormM mapping guide : false
> MF20200025248.txt : true
> MouseWithoutBorders : false
> mysql8 manual installation guide.txt : true
> Note that 'FormM mapping guide' and 'MouseWithoutBorders' are directories and they do not match the 'txt' suffix criterion, however, they were still listed. I think this is what needs to be fixed, not excluding the whole directories like I was doing earlier.

This can be resolved in way similar to my previous comment. We add a flag to `FileTransferSetup` that limits to file only and we update the `com.tcdng.unify.core.file.FileFilter` and its constructor to accommodate this.

**Comment by kodePhile** [comment]
> This can be resolved in way similar to my previous comment. We add a flag to `FileTransferSetup` that limits to file only and we update the `com.tcdng.unify.core.file.FileFilter` and its constructor to accommodate this.

Should this flag default to true or false?

**Comment by kodePhile** [comment]
> > This can be resolved in way similar to my previous comment. We add a flag to `FileTransferSetup` that limits to file only and we update the `com.tcdng.unify.core.file.FileFilter` and its constructor to accommodate this.
> 
> Should this flag default to true or false?

Kindly review the changes. For now, the fileOnly flag defaults to false.

**Comment by tcdng** [comment]
> > > This can be resolved in way similar to my previous comment. We add a flag to `FileTransferSetup` that limits to file only and we update the `com.tcdng.unify.core.file.FileFilter` and its constructor to accommodate this.
> > 
> > 
> > Should this flag default to true or false?
> 
> Kindly review the changes. For now, the fileOnly flag defaults to false.

Yes, `fileOnly` should default to false.

Your earlier choice of `caseSensitive` is better than `preserveCase`; it is easier to infer that the setup is case sensitive. With that resolved, we are good. :)

**Comment by kodePhile** [comment]
> > > > This can be resolved in way similar to my previous comment. We add a flag to `FileTransferSetup` that limits to file only and we update the `com.tcdng.unify.core.file.FileFilter` and its constructor to accommodate this.
> > > 
> > > 
> > > Should this flag default to true or false?
> > 
> > 
> > Kindly review the changes. For now, the fileOnly flag defaults to false.
> 
> Yes, `fileOnly` should default to false.
> 
> Your earlier choice of `caseSensitive` is better than `preserveCase`; it is easier to infer that the setup is case sensitive. With that resolved, we are good. :)

Fixed!

**Comment by tcdng** [comment]
Merged to master!

**Pull request merged**
